version: '3.9'
services:
  postgres:
    image: 'postgres:14.1'
    command: postgres -c 'max_connections=100'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=ps
      - POSTGRES_POSTGRES=ps
      - POSTGRES_PASSWORD=ps
  redis:
    image: 'redis:6.2.6'
    ports:
      - "6379:6379"
