name: Run tests

on:
  push: 
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set Up Python 3.10.2
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.2
      - name: Install poetry
        run: pip install poetry
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install package
        run: poetry install
      - name: Run tests
        run: poetry run test